version: '3'

services:
  server:
    container_name: NODEJS_SERVER_IBM
    build: '.'
    volumes:
      - ./:/ibm
      - ./node_modules:/ibm/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '3333:3333'

  db:
    image: 'mongo'
    container_name: MONGODB_IBM
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db